### ISSUE TITLE
Inferring schema of collection in Rust from bson

### ISSUE THREAD

**Issue by nevi-me** [mongodb-rust/mongodb-schema-parser#34]
# Feature Request
## Summary

I'm trying to write something that infers the schema of a collection, so that I can extract said collection to a columnar format like Parquet or Arrow. I would like to pass BSON files directly `SchemaParser::write_bson(doc: &bson::Bson)` to the parser, but I see that the parser only supports JSON and BSON as raw bytes.

Would there be interest in a PR to support `write_bson()`? I appreciate that this might be a library suited for JS or Compass, but the functionality seems useful.

## Expected Behavior

The parser should be able to analyse bson documents directly

## Drawbacks

Unsure, I haven't checked if the function would affect wasm support. If it does, perhaps it could be feature-gated.

~i could work around this by converting the bson document to raw bytes, but I don't like the roundtrip :(~ The `from_raw()` function takes a JS `Uint8Array`, so I can't use that without more potential overhead.

**Comment by lrlna** [comment]
Hey @nevi-me , a `write_bson()` function would be _amazing_! I've been thinking of adding that, but never got around to it. If you're able to do a PR, I'll gladly accept it.
